# Build stage
FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY . .

RUN go build -o /go-docs-generator-action cmd/main.go

# Final stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /go-docs-generator-action /go-docs-generator-action

ENTRYPOINT ["/go-docs-generator-action"]